Repository TABA7-Sseudam/SseuDam, pull requests merged in 2025-02, with the labels that each got.

#53 🚀 랭킹 API 응답 데이터 변경 및 전체 랭킹 조회 기능 추가
  src/main/java/com/taba7_2/sseudam/controller/RankingController.java
  src/main/java/com/taba7_2/sseudam/repository/RankAccountRepository.java
  src/main/java/com/taba7_2/sseudam/service/RankingService.java
Labels: bug, optimization, backend, feature, refactor

#55 포인트 시스템 개선: 오염도 반영 및 부여 방식 조정
  src/main/java/com/taba7_2/sseudam/controller/AIController.java
Labels: enhancement, backend, feature

#60 🚀 AI 분석 결과 응답 데이터 생성 및 포인트 반영 기능 추가
  .gitignore
  ai_server/output/results.json
  src/main/java/com/taba7_2/sseudam/controller/AIController.java
Labels: backend, feature

#65 퀴즈 정답 시 월별 포인트 반영 기능 추가
  src/main/java/com/taba7_2/sseudam/controller/QuizController.java
Labels: backend, feature

#66 🚀 퀴즈 코드 최적화 및 성능 개선
  src/main/java/com/taba7_2/sseudam/controller/QuizController.java
Labels: optimization, enhancement, backend, refactor

#68 material_success 테이블 삭제 및 관련 코드 정리
  src/main/java/com/taba7_2/sseudam/controller/AIController.java
  src/main/java/com/taba7_2/sseudam/model/MaterialSuccess.java
  src/main/java/com/taba7_2/sseudam/repository/MaterialSuccessRepository.java
Labels: optimization, database, backend, cleanup, refactor

#85 🔄 CSS & UI/UX Refactoring 및 코드 최적화 - 애니메이션 개선, 상태 관리 최적화, JSX 오류 수정
  src/main/frontend/.env
  src/main/frontend/package-lock.json
  src/main/frontend/package.json
  src/main/frontend/public/Guide/guide.png
  src/main/frontend/src/components/analysis/TrashLoading.module.css
  src/main/frontend/src/components/analysis/TrashLoading.tsx
  src/main/frontend/src/components/analysis/WasteAnalysisPage.module.css
  src/main/frontend/src/components/analysis/WasteAnalysisPage.tsx
  src/main/frontend/src/components/auth/RegisterPage.tsx
  src/main/frontend/src/components/dashboard/RecyclingStats.tsx
  src/main/frontend/src/components/guide/GuidePage.tsx
  src/main/frontend/src/components/layout/Minigame.tsx
  src/main/frontend/src/components/profile/UserProfile.tsx
  src/main/frontend/src/components/ranking/Ranking_user.tsx
  src/main/frontend/src/services/api/auth.ts
  src/main/frontend/src/services/api/ranking.ts
  src/main/frontend/src/store/useStore.tsx
  src/main/frontend/src/utils/iconList.ts
Labels: bug, enhancement, UI/UX, refactor, CSS Refactoring

#98 fix: 작업내용 통합
  src/main/frontend/.env
  src/main/frontend/package-lock.json
  src/main/frontend/public/Guide/7.jpg
  src/main/frontend/public/Guide/8.jpg
  src/main/frontend/public/Guide/9.jpg
  src/main/frontend/public/Ranking/11111.png
  src/main/frontend/public/Ranking/2.png
  src/main/frontend/public/Ranking/3.5.2.png
  src/main/frontend/public/Ranking/3.png
  src/main/frontend/public/Ranking/Character_Card.jpg
  src/main/frontend/src/api/axiosInstance.ts
  src/main/frontend/src/components/BulletinBoard/bulletinboard.tsx
  src/main/frontend/src/components/analysis/WasteAnalysisPage.tsx
  src/main/frontend/src/components/guide/GuidePage.tsx
  src/main/frontend/src/components/ranking/Rank_Tier_Guide.tsx
  src/main/frontend/src/components/ranking/Ranking.tsx
  src/main/frontend/src/components/shared/Header.tsx
  src/main/frontend/src/services/api/ranking.ts
Labels: bug, enhancement, feature, UI/UX, frontend, CSS Refactoring

#107 refactor: ai 분석 응답방식 개선 및 하드웨어 응답 개선
  src/main/java/com/taba7_2/sseudam/config/WebSocketConfig.java
  src/main/java/com/taba7_2/sseudam/controller/AIController.java
  src/main/java/com/taba7_2/sseudam/controller/CameraController.java
  src/main/java/com/taba7_2/sseudam/model/AIAnalysisResult.java
  src/main/java/com/taba7_2/sseudam/repository/AIAnalysisResultRepository.java
Labels: backend, refactor, hardware

#114 홈페이지 분리배출 기록 및 분리배출 페이지 카메라 앱 연동 및 백엔드 서버 연동 테스트 완료
  src/main/frontend/.env
  src/main/frontend/package-lock.json
  src/main/frontend/package.json
  src/main/frontend/src/components/analysis/WasteAnalysisPage.tsx
  src/main/frontend/src/components/auth/LoginPage.tsx
  src/main/frontend/src/components/dashboard/RecyclingStats.tsx
  src/main/frontend/src/components/layout/Minigame.tsx
  src/main/frontend/src/components/ranking/Ranking.tsx
  src/main/frontend/src/components/shared/Header.module.scss
  src/main/frontend/src/components/shared/Header.tsx
  src/main/frontend/src/services/api/auth.ts
  src/main/frontend/src/types/auth.ts
  src/main/frontend/tsconfig.json
  src/main/frontend/vite.config.ts
Labels: bug, optimization, enhancement, backend, cleanup, feature, UI/UX, refactor, frontend, Security, AI
